### ISSUE TITLE
Error upon "npm run start"

### ISSUE THREAD

**Issue by cryptocracy** [blockstack/blockstack-app-generator#5]
So I'm trying to test out the Hello Blockstack tutorial on Windows 10 (perhaps thats the problem LOL)

I get stuck at `$ npm run start` 
here is the cli output (see below for debug)
```
$ npm run start

> hello-blockstack@0.0.0 start C:\Users\ty.george\Desktop\hello-blockstack
> npm run browserify; node server.js

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                              node_modules\\npm\\bin\\npm-cli.js" "run" "browserify;" "node" "server.js"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! missing script: browserify;
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Desktop\hello-blockstack\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                              node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hello-blockstack@0.0.0 start: `npm run browserify; node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-blockstack@0.0.0 start script 'npm run browserify;                                                                                               node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hello-blockstack pack                                                                                              age,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run browserify; node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hello-blockstack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hello-blockstack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Desktop\hello-blockstack\npm-debug.log
```
Here is the debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hello-blockstack@0.0.0~prestart: hello-blockstack@0.0.0
6 silly lifecycle hello-blockstack@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle hello-blockstack@0.0.0~start: hello-blockstack@0.0.0
8 verbose lifecycle hello-blockstack@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle hello-blockstack@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\user\Desktop\hello-blockstack\node_modules\.bin;C:\Users\user\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\user\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs;C:\Program Files\PuTTY;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Emulator Manager\1.0;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle hello-blockstack@0.0.0~start: CWD: C:\Users\user\Desktop\hello-blockstack
11 silly lifecycle hello-blockstack@0.0.0~start: Args: [ '/d /s /c', 'npm run browserify; node server.js' ]
12 silly lifecycle hello-blockstack@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle hello-blockstack@0.0.0~start: Failed to exec start script
14 verbose stack Error: hello-blockstack@0.0.0 start: `npm run browserify; node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid hello-blockstack@0.0.0
16 verbose cwd C:\Users\user\Desktop\hello-blockstack
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error hello-blockstack@0.0.0 start: `npm run browserify; node server.js`
22 error Exit status 1
23 error Failed at the hello-blockstack@0.0.0 start script 'npm run browserify; node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the hello-blockstack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run browserify; node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs hello-blockstack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls hello-blockstack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by cryptocracy** [comment]
I thought this might have been something gone wrong with the yeoman generation since I evidently didn't have browserify installed prior.
So I created a fresh directory after installing browserify via npm and then ran the yeoman generator again and then tried to `npm run start` and it throws the same error.

**Comment by shea256** [comment]
Great thanks for reporting @cryptocracy! We'll look into this soon.

**Comment by plyoung** [comment]
any update on this? Just tried it myself (on Win 10) and getting same error.
Simply followed the steps and ended up at the error when I run `npm run start`

**Comment by plyoung** [comment]
@cryptocracy  

Make following change to  `package.json` (replace ; with && in start script command). I also rename the command `browserify ` to `build` but you do not need to do that.

"scripts": {
  "build": "browserify requires.js -o public/bundle.js",
  "start": "npm run build && node server.js"
},

**Comment by plyoung** [comment]
Got new problem now. I click on the "Sign in with Blockstack" button and is send to a page with result "Page Does Not Exist". The URL I was send to it `https://blockstack.org/auth?authRequest=a_long_string_follows.....`

**Comment by Almusamim** [comment]
@plyoung
thanks this worked for me :)

**Comment by cyntechtic** [comment]
```$ npm run start

> hello-blockstack@0.0.0 start C:\Users\GHOST-PROTOCOL\SiteApps\hello-blockstack
> npm run browserify && node server.js

npm WARN invalid config loglevel="notice"

> hello-blockstack@0.0.0 browserify C:\Users\GHOST-PROTOCOL\SiteApps\hello-blockstack
> browserify requires.js -o public/bundle.js

server is listening on 5000
```
though the server is listening on 5000 just curious about this error

```npm WARN invalid config loglevel="notice"```

**Comment by jackzampolin** [comment]
The app has been updated many times since this, and we have fixed this issue. Closing.

**Comment by jsoneaday** [comment]
This issue is still happening as of 11/4/2018, which is really ridiculous. Although the fix does work.

**Comment by Arnoldmn** [comment]
I think your fo;der lacks the node_modules sub folder cause i also had ihe same error and i fixed it by just installing the node module

**Comment by hstove** [comment]
Yes, you must run `npm install` first.
